name: Tenstorrent Backend Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC
  pull_request:
    paths:
      - '.github/workflows/tenstorrent-sdk-ci.yml'

# Auto-cancel superseded runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TT_METAL_VERSION: "v0.63.0"  # Latest stable release (updated 2025-10-13)
  TT_METAL_HOME: /home/runner/tt-metal
  PYTHON_VERSION: '3.10'
  PIP_DISABLE_PIP_VERSION_CHECK: '1'

jobs:
  build-with-sdk:
    runs-on: ubuntu-22.04  # Match tt-metal's supported platform
    steps:
      - name: Checkout TileLang
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-tenstorrent.txt
            pyproject.toml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            llvm \
            libedit-dev \
            libxml2-dev \
            zlib1g-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tenstorrent.txt

      # Note: pip-installed ttnn doesn't include C++ headers needed for building
      # TileLang with USE_REAL_METALIUM=ON. For CI, we use mock mode instead.
      # Real SDK testing should be done locally or in a dedicated workflow that
      # builds tt-metal from source.

      # Enable ccache for faster builds
      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.19
        with:
          key: ${{ runner.os }}-ccache-llvm-metalium-${{ hashFiles('CMakeLists.txt') }}-v1
          max-size: 2G
          create-symlink: true

      # Build TileLang with Tenstorrent backend in mock mode
      - name: Build TileLang with Tenstorrent backend (mock mode)
        run: |
          echo "=== Building TileLang with Tenstorrent Backend (Mock Mode) ==="

          # Configure with mock mode (no real SDK required)
          cmake -B build \
            -G Ninja \
            -DUSE_LLVM=true \
            -DUSE_REAL_METALIUM=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

          # Build
          cmake --build build --config Release -j$(nproc)

      - name: Print ccache stats
        if: always()
        run: |
          if command -v ccache >/dev/null 2>&1; then
            ccache -s
          fi

      - name: Install TileLang Python packages
        run: |
          # Install TVM
          export TVM_LIBRARY_PATH=$(pwd)/build/tvm
          cd 3rdparty/tvm/python
          pip install -e .
          cd ../../..

          # Install TileLang
          pip install -e . --no-build-isolation

      - name: Run Tenstorrent backend tests
        run: |
          export LD_LIBRARY_PATH=$(pwd)/build/tvm:$LD_LIBRARY_PATH

          echo "=== Running Tenstorrent Backend Tests (Mock Mode) ==="
          pytest testing/python/tenstorrent/ -v --tb=short

      - name: Verify code generation works
        run: |
          export LD_LIBRARY_PATH=$(pwd)/build/tvm:$LD_LIBRARY_PATH

          python3 -c '
          import tilelang.tenstorrent as tt
          import tvm
          from tvm import tir

          print("=== Verifying Tenstorrent Code Generation ===")

          # Create simple test module
          A = tir.decl_buffer((256, 256), "float16", name="A")
          B = tir.decl_buffer((256, 256), "float16", name="B")
          C = tir.decl_buffer((256, 256), "float16", name="C")

          func = tir.PrimFunc(params=[A, B, C], body=tir.Evaluate(0))
          func = func.with_attrs({
              "global_symbol": "main",
              "tt_grid_x": 8,
              "tt_grid_y": 8,
              "tt_num_cores": 64,
          })

          mod = tvm.IRModule({"main": func})

          # Apply TT defaults and generate code
          mod = tt.apply_default_schedule(mod)
          artifacts = tt.emit_tt_artifacts(mod)

          # Verify artifacts were generated
          if "main.cpp" in artifacts and len(artifacts["main.cpp"]) > 0:
              print("✅ Code generation successful")
              print(f"  Generated {len(artifacts)} artifacts")
          else:
              print("❌ Code generation failed")
              exit(1)

          print("\n=== Verification Complete ===")
          '
