name: Tenstorrent Backend CI

on:
  pull_request:
    paths:
      - 'tilelang/engine/tt/**'
      - 'testing/python/tt/**'
      - 'tilelang/utils/target.py'
      - '.github/workflows/tenstorrent-ci.yml'
  push:
    branches:
      - main
      - 'ws1-**'

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff black

    - name: Run ruff linter
      run: |
        ruff check tilelang/engine/tt/ testing/python/tt/ --output-format=github

    - name: Run black formatter check
      run: |
        black --check tilelang/engine/tt/ testing/python/tt/

  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/pytorch:23.01-py3
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install build dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export TZ=Etc/UTC
        apt-get update
        apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          git \
          python3-dev \
          zlib1g-dev \
          libedit-dev \
          libxml2-dev

    - name: Set up Python environment
      run: |
        python3 -m pip install --upgrade pip
        pip install pytest pytest-xdist

    - name: Generate TVM cache key
      id: tvm-cache-key
      run: |
        # Cache key based on TVM submodule commit hash
        TVM_COMMIT=$(git rev-parse HEAD:3rdparty/tvm)
        echo "tvm_commit=$TVM_COMMIT" >> $GITHUB_OUTPUT
        echo "TVM submodule at commit: $TVM_COMMIT"

    - name: Cache TVM build
      id: cache-tvm
      uses: actions/cache@v4
      with:
        path: |
          build/libtvm*.so
          build/3rdparty/
        key: tvm-build-cuda-${{ steps.tvm-cache-key.outputs.tvm_commit }}-${{ runner.os }}
        restore-keys: |
          tvm-build-cuda-${{ steps.tvm-cache-key.outputs.tvm_commit }}-
          tvm-build-cuda-

    - name: Build TileLang with CUDA
      run: |
        mkdir -p build
        cd build
        # Create config.cmake for TVM
        cp ../3rdparty/tvm/cmake/config.cmake .
        echo "set(USE_CUDA ON)" >> config.cmake
        echo "set(USE_LLVM OFF)" >> config.cmake

        # Configure with CMake
        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

        # Build (use fewer jobs to avoid OOM on GitHub runners)
        # If cache hit, this will be much faster as TVM is already built
        cmake --build . --config Release -j 2

    - name: Install TileLang
      run: |
        # Copy built libraries to tilelang/lib
        mkdir -p tilelang/lib
        cp build/*.so tilelang/lib/ || true

        # Install Python package in development mode
        pip install -e .

    - name: Run Tenstorrent target registration tests
      run: |
        cd testing/python/tt
        pytest test_target_registration.py -v --tb=short
      continue-on-error: true  # Don't fail if TVM isn't fully available

    - name: Run all Python tests (if TVM available)
      run: |
        cd testing/python
        pytest tt/ -v --tb=short -k "not gpu" || echo "Some tests skipped (no GPU)"
      continue-on-error: true

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install mypy
      run: |
        pip install mypy

    - name: Type check Tenstorrent backend
      run: |
        mypy tilelang/engine/tt/ --ignore-missing-imports || true
      continue-on-error: true
