name: Tenstorrent SDK Integration Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday at midnight UTC
  pull_request:
    paths:
      - '.github/workflows/tenstorrent-sdk-ci.yml'

# Auto-cancel superseded runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TT_METAL_VERSION: "v0.53.0"  # Pin SDK version for reproducibility
  TT_METAL_HOME: /home/runner/tt-metal
  PYTHON_VERSION: '3.10'
  PIP_DISABLE_PIP_VERSION_CHECK: '1'

jobs:
  build-with-sdk:
    runs-on: ubuntu-22.04  # Match tt-metal's supported platform
    steps:
      - name: Checkout TileLang
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-tenstorrent.txt
            pyproject.toml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            llvm \
            libedit-dev \
            libxml2-dev \
            zlib1g-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tenstorrent.txt

      # Cache tt-metal SDK (~1.5GB, version-pinned)
      - name: Cache tt-metal SDK
        id: cache-tt-metal
        uses: actions/cache@v4
        with:
          path: ~/tt-metal
          key: tt-metal-${{ env.TT_METAL_VERSION }}-${{ runner.os }}-v1
          restore-keys: |
            tt-metal-${{ env.TT_METAL_VERSION }}-${{ runner.os }}-
            tt-metal-${{ env.TT_METAL_VERSION }}-

      # Install tt-metal SDK (only if cache miss)
      - name: Install tt-metal SDK
        if: steps.cache-tt-metal.outputs.cache-hit != 'true'
        run: |
          echo "=== Installing TT-Metalium SDK ==="
          echo "Version: $TT_METAL_VERSION"
          echo "Install path: $TT_METAL_HOME"
          echo ""

          # Clone tt-metal with submodules (matches official installation guide)
          git clone --branch $TT_METAL_VERSION --recurse-submodules \
            https://github.com/tenstorrent/tt-metal.git $TT_METAL_HOME

          cd $TT_METAL_HOME

          # Install tt-metal dependencies (libc++, llvm-17, etc.)
          echo "Installing tt-metal dependencies..."
          export DEBIAN_FRONTEND=noninteractive
          sudo -E ./install_dependencies.sh

          # Build tt-metal
          echo "Building tt-metal... (this may take 15-20 minutes)"
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)

          echo "TT-Metalium SDK installed successfully"

      - name: Verify tt-metal SDK
        run: |
          echo "=== Verifying TT-Metalium SDK ==="
          echo "TT_METAL_HOME: $TT_METAL_HOME"

          # Check headers
          if [ -f "$TT_METAL_HOME/tt_metal/host_api.hpp" ]; then
            echo "✅ Headers found"
          else
            echo "❌ Headers missing"
            exit 1
          fi

          # Check libraries
          if [ -f "$TT_METAL_HOME/build/lib/libtt_metal.so" ]; then
            echo "✅ Libraries found"
            ls -lh $TT_METAL_HOME/build/lib/libtt_metal.so
          else
            echo "❌ Libraries missing"
            exit 1
          fi

          # Check package config (if available)
          if [ -f "$TT_METAL_HOME/build/lib/cmake/tt-metalium/tt-metalium-config.cmake" ] || \
             [ -f "$TT_METAL_HOME/build/cmake/tt-metalium-config.cmake" ]; then
            echo "✅ Package config found"
          else
            echo "⚠️  Package config not found (will use FindMetalium.cmake fallback)"
          fi

      # Enable ccache for faster builds
      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.19
        with:
          key: ${{ runner.os }}-ccache-llvm-metalium-${{ hashFiles('CMakeLists.txt') }}-v1
          max-size: 2G
          create-symlink: true

      # Build TileLang with real Metalium
      - name: Build TileLang with real Metalium
        run: |
          echo "=== Building TileLang with Real TT-Metalium SDK ==="

          # Configure
          cmake -B build \
            -G Ninja \
            -DUSE_LLVM=true \
            -DUSE_REAL_METALIUM=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_PREFIX_PATH="$TT_METAL_HOME/build" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

          # Build
          cmake --build build --config Release -j$(nproc)

      - name: Print ccache stats
        if: always()
        run: |
          if command -v ccache >/dev/null 2>&1; then
            ccache -s
          fi

      - name: Install TileLang Python packages
        run: |
          # Install TVM
          export TVM_LIBRARY_PATH=$(pwd)/build/tvm
          cd 3rdparty/tvm/python
          pip install -e .
          cd ../../..

          # Install TileLang
          pip install -e . --no-build-isolation

      - name: Run tests with real Metalium APIs
        run: |
          export LD_LIBRARY_PATH=$(pwd)/build/tvm:$LD_LIBRARY_PATH
          export TT_METAL_HOME=$TT_METAL_HOME

          echo "=== Running Tenstorrent Tests with Real Metalium ==="
          pytest testing/python/tenstorrent/ -v --tb=short

      - name: Verify generated code uses real Metalium APIs
        run: |
          export LD_LIBRARY_PATH=$(pwd)/build/tvm:$LD_LIBRARY_PATH

          python3 -c '
          import tilelang.tenstorrent as tt
          import tvm
          from tvm import tir

          print("=== Verifying Real Metalium API Usage ===")

          # Create simple test module
          A = tir.decl_buffer((256, 256), "float16", name="A")
          B = tir.decl_buffer((256, 256), "float16", name="B")
          C = tir.decl_buffer((256, 256), "float16", name="C")

          func = tir.PrimFunc(params=[A, B, C], body=tir.Evaluate(0))
          func = func.with_attrs({
              "global_symbol": "main",
              "tt_grid_x": 8,
              "tt_grid_y": 8,
              "tt_num_cores": 64,
          })

          mod = tvm.IRModule({"main": func})

          # Apply TT defaults and generate code
          mod = tt.apply_default_schedule(mod)
          artifacts = tt.emit_tt_artifacts(mod)

          # Verify main.cpp uses real Metalium headers (not mock)
          main_cpp = artifacts.get("main.cpp", "")

          # Check for real API includes
          real_api_markers = [
              "#include \"tt_metal/host_api.hpp\"",
              "distributed::MeshDevice",
              "distributed::MeshBuffer",
          ]

          missing = []
          for marker in real_api_markers:
              if marker not in main_cpp:
                  missing.append(marker)

          if missing:
              print(f"❌ Missing real Metalium API markers: {missing}")
              print("\nGenerated code snippet:")
              print(main_cpp[:500])
              exit(1)
          else:
              print("✅ Generated code uses real Metalium APIs")
              print("  - Found tt_metal/host_api.hpp include")
              print("  - Found distributed::MeshDevice usage")
              print("  - Found distributed::MeshBuffer usage")

          print("\n=== Verification Complete ===")
          '

      - name: Test build script with --with-metalium flag
        run: |
          export TT_METAL_HOME=$TT_METAL_HOME

          # Test that build script works with SDK
          bash maint/scripts/local_build_and_test_tt.sh \
            --with-metalium \
            --skip-deps \
            --clean \
            --jobs $(nproc)
