name: Tenstorrent Backend CI

on:
  pull_request:
    paths:
      - 'tilelang/engine/tt/**'
      - 'testing/python/tt/**'
      - 'tilelang/utils/target.py'
      - '.github/workflows/tenstorrent-ci.yml'
  push:
    branches:
      - main
      - 'ws1-**'

# Auto-cancel superseded runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.10'
  PIP_DISABLE_PIP_VERSION_CHECK: '1'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          # Include any file that can affect the lock of Python deps
          cache-dependency-path: |
            requirements-lint.txt
            requirements-dev.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lint.txt

      - name: Run format.sh check
        run: |
          bash format.sh
          # Fail if the formatter changed files
          if ! git diff --quiet; then
            echo "Code formatting issues found."
            git diff
            exit 1
          fi

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-test.txt
            requirements-build.txt
            requirements.txt
            pyproject.toml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            llvm \
            libedit-dev \
            libxml2-dev \
            zlib1g-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      # Compiler cache persisted via GitHub Actions cache
      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2.19
        with:
          # Separate cache per OS and a coarse input set (tune as needed)
          key: ${{ runner.os }}-ccache-${{ hashFiles('CMakeLists.txt', '3rdparty/tvm/**', 'tilelang/**') }}
          max-size: 2G
          create-symlink: true

      - name: Generate TVM cache key
        id: tvm-cache-key
        run: |
          # Cache key based on TVM submodule commit hash
          TVM_COMMIT=$(git rev-parse HEAD:3rdparty/tvm)
          echo "tvm_commit=$TVM_COMMIT" >> $GITHUB_OUTPUT
          echo "TVM submodule at commit: $TVM_COMMIT"

      - name: Cache TVM build
        id: cache-tvm
        uses: actions/cache@v4
        with:
          path: |
            build/libtvm*.so
            build/3rdparty/
          key: tvm-build-llvm-${{ steps.tvm-cache-key.outputs.tvm_commit }}-${{ runner.os }}
          restore-keys: |
            tvm-build-llvm-${{ steps.tvm-cache-key.outputs.tvm_commit }}-
            tvm-build-llvm-

      - name: Build TileLang with LLVM (ccache-enabled)
        run: |
          mkdir -p build
          cd build
          # Create config.cmake for TVM
          cp ../3rdparty/tvm/cmake/config.cmake .
          echo "set(USE_LLVM ON)" >> config.cmake
          echo "set(USE_CUDA OFF)" >> config.cmake
          # Configure with CMake; enable ccache via compiler launcher
          cmake .. \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          # Build (use fewer jobs to avoid OOM on GitHub runners)
          cmake --build . --config Release -j 2

      - name: Cache full build directory
        uses: actions/cache@v4
        with:
          path: build/
          key: tilelang-build-full-${{ steps.tvm-cache-key.outputs.tvm_commit }}-${{ runner.os }}
          restore-keys: tilelang-build-full-${{ steps.tvm-cache-key.outputs.tvm_commit }}-

      - name: Install TileLang
        run: |
          # Copy built libraries to tilelang/lib
          mkdir -p tilelang/lib
          cp build/*.so tilelang/lib/ || true
          export USE_LLVM=true
          pip install -e .

      - name: Print ccache stats
        if: always()
        run: ccache -s || true

      - name: Run Tenstorrent target registration tests
        run: |
          cd testing/python/tt
          pytest test_target_registration.py -v --tb=short
        continue-on-error: true  # Don't fail if TVM isn't fully available

      - name: Run all Python tests (if TVM available)
        run: |
          cd testing/python
          pytest tt/ -v --tb=short -k "not gpu" || echo "Some tests skipped (no GPU)"
        continue-on-error: true

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: |
            requirements-mypy.txt
            pyproject.toml

      - name: Install mypy
        run: pip install -r requirements-mypy.txt

      - name: Type check Tenstorrent backend
        run: mypy tilelang/engine/tt/ --ignore-missing-imports || true
        continue-on-error: true